
[ball]
# Venstre kamera (index 4):
hsv_min_left = [40, 35, 75]   #
hsv_max_left = [93, 255, 135]  

# Høgre kamera 
hsv_min_right = [35, 35, 50]  
hsv_max_right = [93, 255, 135] 

# Fallback verdiar 
hsv_min = [35, 35, 50]   
hsv_max = [93, 255, 135] 

min_radius = 3.8
min_area = 35
circularity_threshold = 0.40

[filter]
brightness = -10
saturation = 2.4
vibrance = 0.1
sharpness = 0.9

[debug]
show_fps = true

[performance]
blur_kernel_size = 7
morph_iterations = 2 
