
#[ball]
# Venstre kamera 
#hsv_min_left = [35, 5, 70]   
#hsv_max_left = [96, 255, 175]  

# Hogre kamera 
#hsv_min_right = [67, 10, 30]   
#hsv_max_right = [92, 255, 220]

# Fallback verdiar 
#hsv_min = [40, 40, 40]   
#hsv_max = [93, 255, 135] 

#min_radius = 3.8
#min_area = 35
#circularity_threshold = 0.70

#[performance]
#blur_kernel_size = 5
#morph_iterations = 1 

#[camera_filters]

#brightness = -10    
#saturation = 2.4     
#vibrance = 0.1        
#sharpness = 0.9        


#[network]
#host = "127.0.0.1" 
#port = 5555        


#[camera]

#left_index = 0     
#right_index = 6    

#width = 680
#height = 460

#fps = 20
#fov = 60
#auto_exposure = false