
[ball]
# Venstre kamera (index 4):
hsv_min_left = [40, 35, 75]   #
hsv_max_left = [93, 255, 135]  

# Høgre kamera 
hsv_min_right = [35, 35, 50]  
hsv_max_right = [93, 255, 135] 

# Fallback verdiar 
hsv_min = [35, 35, 50]   
hsv_max = [93, 255, 135] 

min_radius = 3.8
min_area = 35
circularity_threshold = 0.40

[performance]
blur_kernel_size = 7
morph_iterations = 2 

[grid]
origin_x = 0.0   
origin_y = 0.0   
cell = 25.0       

[network]
host = "127.0.0.1"  
port = 5555        

[camera]

left_index = 4      # Venstre kamera
right_index = 6     # Høgre kamera

# oppløysing
width = 800
height = 720

fps = 30
fov = 60
auto_exposure = true


[debug]
show_fps = true
log_detections = true  # Satt til true for testing
save_debug_images = false   
